meta_title: "Salesquare - Discover The Latest Fashion Sales"
meta_description: "Discover The Latest Fashion Sales"
meta_image: "banner.jpg" # Less than 1MB and more than 1000px width
twitter_account: "@shopsalesquare"
