# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f919c3e6663cc33a791868d9ec0287b55c838d7028a83590dc9f40cd20765c2a920117759aafe5d5045fc2ecd0e426c6a9c61ac278028377016715c1fd76dfd7

test:
  secret_key_base: 39088bc64a19b55e1e18c41dddd0580dc741571b5f10984d535f3579fbb4585a88ab53a964c6b7afa7d1506139b171270dd6710722a7fb03f049253d7de899e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
